setup: Use `pip3 install`'s --upgrade switch, might fix CI
Previously, setup.sh Travis CI run broke at:

    Requirement already satisfied: numpy in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.16.4)
    ...
    Successfully built sklearn
    ERROR: scipy 1.6.1 has requirement numpy>=1.16.5, but you'll have numpy 1.16.4 which is incompatible.
    ERROR: scikit-image 0.18.1 has requirement numpy>=1.16.5, but you'll have numpy 1.16.4 which is incompatible.
    Installing collected packages: lmdb, ...